ekyna_verified_reviews_api_reviews:
    path: /api/reviews/{productId}/{page}
    controller: Ekyna\Bundle\VerifiedReviewsBundle\Controller\ApiController::reviews
    methods: [GET]
    defaults:
        page: 0
    requirements:
        productId: \d+
        page: \d+
    options:
        expose: true
